Repository JupiterOne/graph-google-cloud, pull requests merged in 2022-09, with the labels that each got.

#529 Add auto versioning
  .github/workflows/build.yml
  .gitignore
  README.md
  package.json
  yarn.lock
Labels: minor

#538 Removed information about changelog format
  .prettierignore
  CHANGELOG.md
Labels: patch

#521 INT-5355 upgrade googleapis to support WorkerPools
  package.json
  yarn.lock
Labels: minor

#534 INT-5445 Fix Entity _class for Cloud Build
  docs/jupiterone.md
  src/steps/cloud-build/constants.ts
  src/steps/cloud-build/converters.ts
  src/steps/cloud-build/steps/__recordings__/fetch-cloud-build-triggers_3640668212/recording.har
  src/steps/cloud-build/steps/__recordings__/fetch-cloud-builds_695874263/recording.har
Labels: minor, patch

#523 INT-5235 step: fetch-cloud-build-worker-pools
  docs/jupiterone.md
  src/getStepStartStates.ts
  src/index.test.ts
  src/steps/cloud-build/client.ts
  src/steps/cloud-build/constants.ts
  src/steps/cloud-build/converters.ts
  src/steps/cloud-build/index.ts
  src/steps/cloud-build/steps/__recordings__/fetch-cloud-build-worker-pools_2944204433/recording.har
  src/steps/cloud-build/steps/fetch-cloud-build-triggers.ts
  src/steps/cloud-build/steps/fetch-cloud-build-worker-pools.test.ts
  src/steps/cloud-build/steps/fetch-cloud-build-worker-pools.ts
Labels: minor

#524 INT-5355 upgrade googleapis to support GithubEnterpriseConfigs
  package.json
  yarn.lock
Labels: minor

#525 INT-5236: step-fetch-cloud-build-ghe-configs
  docs/jupiterone.md
  src/getStepStartStates.ts
  src/index.test.ts
  src/steps/cloud-build/client.ts
  src/steps/cloud-build/constants.ts
  src/steps/cloud-build/converters.ts
  src/steps/cloud-build/index.ts
  src/steps/cloud-build/steps/__recordings__/fetch-cloud-build-ghe-configs_3514519803/recording.har
  src/steps/cloud-build/steps/fetch-cloud-build-ghe-configs.test.ts
  src/steps/cloud-build/steps/fetch-cloud-build-ghe-configs.ts
  test/recording.ts
Labels: minor

#526 INT-5395 upgrade googleapis to support BitbucketServerConfigs
  package.json
  yarn.lock
Labels: minor

#531 INT-5237 step: fetch-cloud-build-bb-configs
  docs/jupiterone.md
  src/getStepStartStates.ts
  src/index.test.ts
  src/steps/cloud-build/client.ts
  src/steps/cloud-build/constants.ts
  src/steps/cloud-build/converters.ts
  src/steps/cloud-build/index.ts
  src/steps/cloud-build/steps/__recordings__/fetch-cloud-build-bb-configs_3549344971/recording.har
  src/steps/cloud-build/steps/fetch-cloud-build-bb-configs.test.ts
  src/steps/cloud-build/steps/fetch-cloud-build-bb-configs.ts
  test/recording.ts
Labels: minor

#532 INT-5238/INT-5292 step: fetch-cloud-build-bb-repos / relationship: google_cloud_bitbucket_server_config_has_repo
  docs/jupiterone.md
  src/getStepStartStates.ts
  src/index.test.ts
  src/steps/cloud-build/client.ts
  src/steps/cloud-build/constants.ts
  src/steps/cloud-build/converters.ts
  src/steps/cloud-build/index.ts
  src/steps/cloud-build/steps/__recordings__/fetch-cloud-build-bb-repos_1051036273/recording.har
  src/steps/cloud-build/steps/fetch-cloud-build-bb-configs.ts
  src/steps/cloud-build/steps/fetch-cloud-build-bb-repos.test.ts
  src/steps/cloud-build/steps/fetch-cloud-build-bb-repos.ts
  src/steps/cloud-build/steps/fetch-cloud-build-ghe-configs.ts
  src/steps/cloud-build/steps/fetch-cloud-build-triggers.ts
  src/steps/cloud-build/steps/fetch-cloud-build-worker-pools.ts
  src/steps/cloud-build/steps/fetch-cloud-builds.ts
Labels: minor

#537 INT-5288 step: build-cloud-build-storage-bucket-relationships
  docs/jupiterone.md
  src/getStepStartStates.ts
  src/index.test.ts
  src/steps/cloud-build/constants.ts
  src/steps/cloud-build/index.ts
  src/steps/cloud-build/steps/__recordings__/build-cloud-build-uses-storage-bucket-relationships_4186298260/recording.har
  src/steps/cloud-build/steps/build-cloud-build-uses-storage-bucket-relationships.test.ts
  src/steps/cloud-build/steps/build-cloud-build-uses-storage-bucket-relationships.ts
  test/recording.ts
Labels: minor

#540 INT-5545 step: fetch-cloud-source-repositories
  docs/jupiterone.md
  src/__recordings__/getStepStartStates_2244155193/recording.har
  src/getStepStartStates.ts
  src/google-cloud/types.ts
  src/index.test.ts
  src/steps/cloud-source-repositories/client.ts
  src/steps/cloud-source-repositories/constants.ts
  src/steps/cloud-source-repositories/converters.ts
  src/steps/cloud-source-repositories/index.ts
  src/steps/cloud-source-repositories/steps/__recordings__/fetch-cloud-source-repositories_476209090/recording.har
  src/steps/cloud-source-repositories/steps/fetch-cloud-source-repositories.test.ts
  src/steps/cloud-source-repositories/steps/fetch-cloud-source-repositories.ts
  src/steps/steps.ts
Labels: minor

#541 INT-5289 step: build-cloud-build-uses-source-repo-relationships
  docs/jupiterone.md
  src/getStepStartStates.ts
  src/index.test.ts
  src/steps/cloud-build/constants.ts
  src/steps/cloud-build/index.ts
  src/steps/cloud-build/steps/__recordings__/build-cloud-build-uses-source-repo-relationships_1963102466/recording.har
  src/steps/cloud-build/steps/build-cloud-build-uses-source-repo-relationships.test.ts
  src/steps/cloud-build/steps/build-cloud-build-uses-source-repo-relationships.ts
Labels: minor

#543 Remove checkout code from old versioning method
  .github/workflows/build.yml
Labels: minor, release

#546 INT-5579 Decouple `iterateApi` into `forEachPage` and `withErrorHandling`
  src/google-cloud/client.test.ts
  src/google-cloud/client.ts
  src/steps/cloud-run/client.ts
  src/steps/compute/client.ts
  src/steps/sql-admin/client.ts
Labels: patch, release

#551 Account for non-deterministic basic role permissions
  package.json
  src/steps/cloud-asset/__snapshots__/index.test.ts.snap
  src/steps/iam/basic-permissions/editor.ts
  src/steps/iam/basic-permissions/owner.ts
  src/steps/iam/basic-permissions/viewer.ts
  src/steps/iam/client.ts
  src/steps/iam/index.ts
Labels: patch, release
